packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  sharp: true
catalog:
  "@libsql/client": 0.15.15
  "@orpc/ai-sdk": ^1.13.14
  "@orpc/client": ^1.13.14
  "@orpc/openapi": ^1.13.14
  "@orpc/server": ^1.13.14
  "@orpc/zod": ^1.13.14
  "@types/node": ^25.6.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  better-auth: 1.5.5
  dotenv: ^17.4.2
  libsql: 0.5.22
  lucide-react: ^1.8.0
  next-themes: ^0.4.6
  react: ^19.2.5
  react-dom: ^19.2.5
  sonner: ^2.0.7
  tailwindcss: ^4.2.2
  zod: ^4.3.6
  "evlog": "^2.13.0"
