/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ScoreCvRouteImport } from './routes/score-cv'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as OptimizadorLinkedinRouteImport } from './routes/optimizador-linkedin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CrearCvRouteImport } from './routes/crear-cv'
import { Route as CoachingRouteImport } from './routes/coaching'
import { Route as CartaDePresentacionRouteImport } from './routes/carta-de-presentacion'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ApiResumeSuggestionsRouteImport } from './routes/api/resume-suggestions'
import { Route as ProtectedSetupRouteImport } from './routes/_protected/setup'
import { Route as ProtectedDashRouteRouteImport } from './routes/_protected/dash/route'
import { Route as ProtectedDashIndexRouteImport } from './routes/_protected/dash/index'
import { Route as ApiWebhooksResendRouteImport } from './routes/api/webhooks/resend'
import { Route as ApiWebhooksMercadopagoRouteImport } from './routes/api/webhooks/mercadopago'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedDashSuggestedRouteImport } from './routes/_protected/dash/suggested'
import { Route as ProtectedDashCoachesRouteImport } from './routes/_protected/dash/coaches'
import { Route as ProtectedDashAgentsRouteImport } from './routes/_protected/dash/agents'
import { Route as ProtectedDashResumesIndexRouteImport } from './routes/_protected/dash/resumes/index'
import { Route as ProtectedDashLettersIndexRouteImport } from './routes/_protected/dash/letters/index'
import { Route as ApiWebhooksCalSplatRouteImport } from './routes/api/webhooks/cal/$'
import { Route as ProtectedDashResumesResumeIdRouteImport } from './routes/_protected/dash/resumes/$resumeId'
import { Route as ProtectedDashLettersGenerationIdRouteImport } from './routes/_protected/dash/letters/$generationId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreCvRoute = ScoreCvRouteImport.update({
  id: '/score-cv',
  path: '/score-cv',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizadorLinkedinRoute = OptimizadorLinkedinRouteImport.update({
  id: '/optimizador-linkedin',
  path: '/optimizador-linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearCvRoute = CrearCvRouteImport.update({
  id: '/crear-cv',
  path: '/crear-cv',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingRoute = CoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaDePresentacionRoute = CartaDePresentacionRouteImport.update({
  id: '/carta-de-presentacion',
  path: '/carta-de-presentacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResumeSuggestionsRoute = ApiResumeSuggestionsRouteImport.update({
  id: '/api/resume-suggestions',
  path: '/api/resume-suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSetupRoute = ProtectedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashRouteRoute = ProtectedDashRouteRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashIndexRoute = ProtectedDashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedDashRouteRoute,
} as any)
const ApiWebhooksResendRoute = ApiWebhooksResendRouteImport.update({
  id: '/api/webhooks/resend',
  path: '/api/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMercadopagoRoute = ApiWebhooksMercadopagoRouteImport.update({
  id: '/api/webhooks/mercadopago',
  path: '/api/webhooks/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashSuggestedRoute = ProtectedDashSuggestedRouteImport.update({
  id: '/suggested',
  path: '/suggested',
  getParentRoute: () => ProtectedDashRouteRoute,
} as any)
const ProtectedDashCoachesRoute = ProtectedDashCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => ProtectedDashRouteRoute,
} as any)
const ProtectedDashAgentsRoute = ProtectedDashAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ProtectedDashRouteRoute,
} as any)
const ProtectedDashResumesIndexRoute =
  ProtectedDashResumesIndexRouteImport.update({
    id: '/resumes/',
    path: '/resumes/',
    getParentRoute: () => ProtectedDashRouteRoute,
  } as any)
const ProtectedDashLettersIndexRoute =
  ProtectedDashLettersIndexRouteImport.update({
    id: '/letters/',
    path: '/letters/',
    getParentRoute: () => ProtectedDashRouteRoute,
  } as any)
const ApiWebhooksCalSplatRoute = ApiWebhooksCalSplatRouteImport.update({
  id: '/api/webhooks/cal/$',
  path: '/api/webhooks/cal/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashResumesResumeIdRoute =
  ProtectedDashResumesResumeIdRouteImport.update({
    id: '/resumes/$resumeId',
    path: '/resumes/$resumeId',
    getParentRoute: () => ProtectedDashRouteRoute,
  } as any)
const ProtectedDashLettersGenerationIdRoute =
  ProtectedDashLettersGenerationIdRouteImport.update({
    id: '/letters/$generationId',
    path: '/letters/$generationId',
    getParentRoute: () => ProtectedDashRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carta-de-presentacion': typeof CartaDePresentacionRoute
  '/coaching': typeof CoachingRoute
  '/crear-cv': typeof CrearCvRoute
  '/login': typeof LoginRoute
  '/optimizador-linkedin': typeof OptimizadorLinkedinRoute
  '/policy': typeof PolicyRoute
  '/pricing': typeof PricingRoute
  '/score-cv': typeof ScoreCvRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/dash': typeof ProtectedDashRouteRouteWithChildren
  '/setup': typeof ProtectedSetupRoute
  '/api/resume-suggestions': typeof ApiResumeSuggestionsRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/dash/agents': typeof ProtectedDashAgentsRoute
  '/dash/coaches': typeof ProtectedDashCoachesRoute
  '/dash/suggested': typeof ProtectedDashSuggestedRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/dash/': typeof ProtectedDashIndexRoute
  '/dash/letters/$generationId': typeof ProtectedDashLettersGenerationIdRoute
  '/dash/resumes/$resumeId': typeof ProtectedDashResumesResumeIdRoute
  '/api/webhooks/cal/$': typeof ApiWebhooksCalSplatRoute
  '/dash/letters/': typeof ProtectedDashLettersIndexRoute
  '/dash/resumes/': typeof ProtectedDashResumesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carta-de-presentacion': typeof CartaDePresentacionRoute
  '/coaching': typeof CoachingRoute
  '/crear-cv': typeof CrearCvRoute
  '/login': typeof LoginRoute
  '/optimizador-linkedin': typeof OptimizadorLinkedinRoute
  '/policy': typeof PolicyRoute
  '/pricing': typeof PricingRoute
  '/score-cv': typeof ScoreCvRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/setup': typeof ProtectedSetupRoute
  '/api/resume-suggestions': typeof ApiResumeSuggestionsRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/dash/agents': typeof ProtectedDashAgentsRoute
  '/dash/coaches': typeof ProtectedDashCoachesRoute
  '/dash/suggested': typeof ProtectedDashSuggestedRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/dash': typeof ProtectedDashIndexRoute
  '/dash/letters/$generationId': typeof ProtectedDashLettersGenerationIdRoute
  '/dash/resumes/$resumeId': typeof ProtectedDashResumesResumeIdRoute
  '/api/webhooks/cal/$': typeof ApiWebhooksCalSplatRoute
  '/dash/letters': typeof ProtectedDashLettersIndexRoute
  '/dash/resumes': typeof ProtectedDashResumesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/carta-de-presentacion': typeof CartaDePresentacionRoute
  '/coaching': typeof CoachingRoute
  '/crear-cv': typeof CrearCvRoute
  '/login': typeof LoginRoute
  '/optimizador-linkedin': typeof OptimizadorLinkedinRoute
  '/policy': typeof PolicyRoute
  '/pricing': typeof PricingRoute
  '/score-cv': typeof ScoreCvRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/_protected/dash': typeof ProtectedDashRouteRouteWithChildren
  '/_protected/setup': typeof ProtectedSetupRoute
  '/api/resume-suggestions': typeof ApiResumeSuggestionsRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/_protected/dash/agents': typeof ProtectedDashAgentsRoute
  '/_protected/dash/coaches': typeof ProtectedDashCoachesRoute
  '/_protected/dash/suggested': typeof ProtectedDashSuggestedRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/_protected/dash/': typeof ProtectedDashIndexRoute
  '/_protected/dash/letters/$generationId': typeof ProtectedDashLettersGenerationIdRoute
  '/_protected/dash/resumes/$resumeId': typeof ProtectedDashResumesResumeIdRoute
  '/api/webhooks/cal/$': typeof ApiWebhooksCalSplatRoute
  '/_protected/dash/letters/': typeof ProtectedDashLettersIndexRoute
  '/_protected/dash/resumes/': typeof ProtectedDashResumesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carta-de-presentacion'
    | '/coaching'
    | '/crear-cv'
    | '/login'
    | '/optimizador-linkedin'
    | '/policy'
    | '/pricing'
    | '/score-cv'
    | '/status'
    | '/terms'
    | '/dash'
    | '/setup'
    | '/api/resume-suggestions'
    | '/api/uploadthing'
    | '/dash/agents'
    | '/dash/coaches'
    | '/dash/suggested'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/webhooks/mercadopago'
    | '/api/webhooks/resend'
    | '/dash/'
    | '/dash/letters/$generationId'
    | '/dash/resumes/$resumeId'
    | '/api/webhooks/cal/$'
    | '/dash/letters/'
    | '/dash/resumes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carta-de-presentacion'
    | '/coaching'
    | '/crear-cv'
    | '/login'
    | '/optimizador-linkedin'
    | '/policy'
    | '/pricing'
    | '/score-cv'
    | '/status'
    | '/terms'
    | '/setup'
    | '/api/resume-suggestions'
    | '/api/uploadthing'
    | '/dash/agents'
    | '/dash/coaches'
    | '/dash/suggested'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/webhooks/mercadopago'
    | '/api/webhooks/resend'
    | '/dash'
    | '/dash/letters/$generationId'
    | '/dash/resumes/$resumeId'
    | '/api/webhooks/cal/$'
    | '/dash/letters'
    | '/dash/resumes'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/carta-de-presentacion'
    | '/coaching'
    | '/crear-cv'
    | '/login'
    | '/optimizador-linkedin'
    | '/policy'
    | '/pricing'
    | '/score-cv'
    | '/status'
    | '/terms'
    | '/_protected/dash'
    | '/_protected/setup'
    | '/api/resume-suggestions'
    | '/api/uploadthing'
    | '/_protected/dash/agents'
    | '/_protected/dash/coaches'
    | '/_protected/dash/suggested'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/webhooks/mercadopago'
    | '/api/webhooks/resend'
    | '/_protected/dash/'
    | '/_protected/dash/letters/$generationId'
    | '/_protected/dash/resumes/$resumeId'
    | '/api/webhooks/cal/$'
    | '/_protected/dash/letters/'
    | '/_protected/dash/resumes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  CartaDePresentacionRoute: typeof CartaDePresentacionRoute
  CoachingRoute: typeof CoachingRoute
  CrearCvRoute: typeof CrearCvRoute
  LoginRoute: typeof LoginRoute
  OptimizadorLinkedinRoute: typeof OptimizadorLinkedinRoute
  PolicyRoute: typeof PolicyRoute
  PricingRoute: typeof PricingRoute
  ScoreCvRoute: typeof ScoreCvRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  ApiResumeSuggestionsRoute: typeof ApiResumeSuggestionsRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiWebhooksMercadopagoRoute: typeof ApiWebhooksMercadopagoRoute
  ApiWebhooksResendRoute: typeof ApiWebhooksResendRoute
  ApiWebhooksCalSplatRoute: typeof ApiWebhooksCalSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score-cv': {
      id: '/score-cv'
      path: '/score-cv'
      fullPath: '/score-cv'
      preLoaderRoute: typeof ScoreCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimizador-linkedin': {
      id: '/optimizador-linkedin'
      path: '/optimizador-linkedin'
      fullPath: '/optimizador-linkedin'
      preLoaderRoute: typeof OptimizadorLinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear-cv': {
      id: '/crear-cv'
      path: '/crear-cv'
      fullPath: '/crear-cv'
      preLoaderRoute: typeof CrearCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching': {
      id: '/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carta-de-presentacion': {
      id: '/carta-de-presentacion'
      path: '/carta-de-presentacion'
      fullPath: '/carta-de-presentacion'
      preLoaderRoute: typeof CartaDePresentacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume-suggestions': {
      id: '/api/resume-suggestions'
      path: '/api/resume-suggestions'
      fullPath: '/api/resume-suggestions'
      preLoaderRoute: typeof ApiResumeSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/setup': {
      id: '/_protected/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof ProtectedSetupRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dash': {
      id: '/_protected/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof ProtectedDashRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dash/': {
      id: '/_protected/dash/'
      path: '/'
      fullPath: '/dash/'
      preLoaderRoute: typeof ProtectedDashIndexRouteImport
      parentRoute: typeof ProtectedDashRouteRoute
    }
    '/api/webhooks/resend': {
      id: '/api/webhooks/resend'
      path: '/api/webhooks/resend'
      fullPath: '/api/webhooks/resend'
      preLoaderRoute: typeof ApiWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mercadopago': {
      id: '/api/webhooks/mercadopago'
      path: '/api/webhooks/mercadopago'
      fullPath: '/api/webhooks/mercadopago'
      preLoaderRoute: typeof ApiWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dash/suggested': {
      id: '/_protected/dash/suggested'
      path: '/suggested'
      fullPath: '/dash/suggested'
      preLoaderRoute: typeof ProtectedDashSuggestedRouteImport
      parentRoute: typeof ProtectedDashRouteRoute
    }
    '/_protected/dash/coaches': {
      id: '/_protected/dash/coaches'
      path: '/coaches'
      fullPath: '/dash/coaches'
      preLoaderRoute: typeof ProtectedDashCoachesRouteImport
      parentRoute: typeof ProtectedDashRouteRoute
    }
    '/_protected/dash/agents': {
      id: '/_protected/dash/agents'
      path: '/agents'
      fullPath: '/dash/agents'
      preLoaderRoute: typeof ProtectedDashAgentsRouteImport
      parentRoute: typeof ProtectedDashRouteRoute
    }
    '/_protected/dash/resumes/': {
      id: '/_protected/dash/resumes/'
      path: '/resumes'
      fullPath: '/dash/resumes/'
      preLoaderRoute: typeof ProtectedDashResumesIndexRouteImport
      parentRoute: typeof ProtectedDashRouteRoute
    }
    '/_protected/dash/letters/': {
      id: '/_protected/dash/letters/'
      path: '/letters'
      fullPath: '/dash/letters/'
      preLoaderRoute: typeof ProtectedDashLettersIndexRouteImport
      parentRoute: typeof ProtectedDashRouteRoute
    }
    '/api/webhooks/cal/$': {
      id: '/api/webhooks/cal/$'
      path: '/api/webhooks/cal/$'
      fullPath: '/api/webhooks/cal/$'
      preLoaderRoute: typeof ApiWebhooksCalSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dash/resumes/$resumeId': {
      id: '/_protected/dash/resumes/$resumeId'
      path: '/resumes/$resumeId'
      fullPath: '/dash/resumes/$resumeId'
      preLoaderRoute: typeof ProtectedDashResumesResumeIdRouteImport
      parentRoute: typeof ProtectedDashRouteRoute
    }
    '/_protected/dash/letters/$generationId': {
      id: '/_protected/dash/letters/$generationId'
      path: '/letters/$generationId'
      fullPath: '/dash/letters/$generationId'
      preLoaderRoute: typeof ProtectedDashLettersGenerationIdRouteImport
      parentRoute: typeof ProtectedDashRouteRoute
    }
  }
}

interface ProtectedDashRouteRouteChildren {
  ProtectedDashAgentsRoute: typeof ProtectedDashAgentsRoute
  ProtectedDashCoachesRoute: typeof ProtectedDashCoachesRoute
  ProtectedDashSuggestedRoute: typeof ProtectedDashSuggestedRoute
  ProtectedDashIndexRoute: typeof ProtectedDashIndexRoute
  ProtectedDashLettersGenerationIdRoute: typeof ProtectedDashLettersGenerationIdRoute
  ProtectedDashResumesResumeIdRoute: typeof ProtectedDashResumesResumeIdRoute
  ProtectedDashLettersIndexRoute: typeof ProtectedDashLettersIndexRoute
  ProtectedDashResumesIndexRoute: typeof ProtectedDashResumesIndexRoute
}

const ProtectedDashRouteRouteChildren: ProtectedDashRouteRouteChildren = {
  ProtectedDashAgentsRoute: ProtectedDashAgentsRoute,
  ProtectedDashCoachesRoute: ProtectedDashCoachesRoute,
  ProtectedDashSuggestedRoute: ProtectedDashSuggestedRoute,
  ProtectedDashIndexRoute: ProtectedDashIndexRoute,
  ProtectedDashLettersGenerationIdRoute: ProtectedDashLettersGenerationIdRoute,
  ProtectedDashResumesResumeIdRoute: ProtectedDashResumesResumeIdRoute,
  ProtectedDashLettersIndexRoute: ProtectedDashLettersIndexRoute,
  ProtectedDashResumesIndexRoute: ProtectedDashResumesIndexRoute,
}

const ProtectedDashRouteRouteWithChildren =
  ProtectedDashRouteRoute._addFileChildren(ProtectedDashRouteRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashRouteRoute: typeof ProtectedDashRouteRouteWithChildren
  ProtectedSetupRoute: typeof ProtectedSetupRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashRouteRoute: ProtectedDashRouteRouteWithChildren,
  ProtectedSetupRoute: ProtectedSetupRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  CartaDePresentacionRoute: CartaDePresentacionRoute,
  CoachingRoute: CoachingRoute,
  CrearCvRoute: CrearCvRoute,
  LoginRoute: LoginRoute,
  OptimizadorLinkedinRoute: OptimizadorLinkedinRoute,
  PolicyRoute: PolicyRoute,
  PricingRoute: PricingRoute,
  ScoreCvRoute: ScoreCvRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  ApiResumeSuggestionsRoute: ApiResumeSuggestionsRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiWebhooksMercadopagoRoute: ApiWebhooksMercadopagoRoute,
  ApiWebhooksResendRoute: ApiWebhooksResendRoute,
  ApiWebhooksCalSplatRoute: ApiWebhooksCalSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
